/** Premium portfolio photography — bundled JPGs in /public/portfolio */
export const PORTFOLIO_VISUALS = {
  realestate: {
    brand: 'Marina Heights',
    brandAr: 'مارينا هايتس',
    tagline: 'Luxury waterfront living · West Bay, Doha',
    taglineAr: 'عيش فاخر على الواجهة · الخليج الغربي · الدوحة',
    hero: '/portfolio/realestate-hero.jpg',
    preview: '/portfolio/realestate-hero.jpg',
    services: [
      { name: 'Penthouse', nameAr: 'Penthouse', img: '/portfolio/realestate-s1.jpg', tone: '#BBDEFB', tone2: '#0D47A1', icon: 'building' },
      { name: 'Marina View', nameAr: 'إطلالة', img: '/portfolio/realestate-s2.jpg', tone: '#B2DFDB', tone2: '#00695C', icon: 'waves' },
      { name: 'Investment', nameAr: 'استثمار', img: '/portfolio/realestate-s3.jpg', tone: '#CFD8DC', tone2: '#37474F', icon: 'trending' },
    ],
    accent: '#4A7CAB',
    accentLight: '#6B9FD4',
    bg: '#F5F8FC',
    dark: '#0A1018',
    nav: ['Properties', 'About', 'Agents', 'Enquire'],
    navAr: ['عقارات', 'من نحن', 'وكلاء', 'استفسار'],
    stat: '38/wk',
    statLabel: 'Leads',
    heroFallback: 'linear-gradient(135deg, #0A1628 0%, #2E6DA8 100%)',
  },
  salon: {
    brand: 'Lumière Salon',
    brandAr: 'صالون لوميير',
    tagline: 'Luxury beauty & spa · Lusail',
    taglineAr: 'جمال وسبا فاخر · لوسيل',
    hero: '/portfolio/salon-hero.jpg',
    preview: '/portfolio/salon-hero.jpg',
    services: [
      { name: 'Hair', nameAr: 'شعر', img: '/portfolio/salon-s1.jpg', tone: '#E1BEE7', tone2: '#7B1FA2', icon: 'scissors' },
      { name: 'Nails', nameAr: 'أظافر', img: '/portfolio/salon-s2.jpg', tone: '#F8BBD9', tone2: '#C2185B', icon: 'sparkles' },
      { name: 'Spa', nameAr: 'سبا', img: '/portfolio/salon-s3.jpg', tone: '#D1C4E9', tone2: '#512DA8', icon: 'heart' },
    ],
    accent: '#9B7BB8',
    accentLight: '#C4A8D8',
    bg: '#FAF8FC',
    dark: '#120E18',
    nav: ['Home', 'Services', 'Gallery', 'Book'],
    navAr: ['الرئيسية', 'الخدمات', 'معرض', 'احجز'],
    stat: '4.9★',
    statLabel: 'Bookings',
    heroFallback: 'linear-gradient(135deg, #1A1028 0%, #7B5BA8 100%)',
  },
  restaurant: {
    brand: 'Saffron Kitchen',
    brandAr: 'مطبخ الزعفران',
    tagline: 'Fine dining · Authentic flavours · Al Wakrah',
    taglineAr: 'مأكولات فاخرة · نكهات أصيلة · الوكرة',
    hero: '/portfolio/restaurant-hero.jpg',
    preview: '/portfolio/restaurant-hero.jpg',
    services: [
      { name: 'Mains', nameAr: 'أطباق', img: '/portfolio/restaurant-s1.jpg', tone: '#FFE0B2', tone2: '#E65100', icon: 'utensils' },
      { name: 'Desserts', nameAr: 'حلويات', img: '/portfolio/restaurant-s2.jpg', tone: '#FFECB3', tone2: '#FF8F00', icon: 'cake' },
      { name: 'Drinks', nameAr: 'مشروبات', img: '/portfolio/restaurant-s3.jpg', tone: '#FFCCBC', tone2: '#BF360C', icon: 'coffee' },
    ],
    accent: '#C4956A',
    accentLight: '#E8C4A0',
    bg: '#FBF9F6',
    dark: '#141010',
    nav: ['Menu', 'Gallery', 'Reserve', 'Contact'],
    navAr: ['القائمة', 'معرض', 'احجز', 'تواصل'],
    stat: '+89/mo',
    statLabel: 'Reservations',
    heroFallback: 'linear-gradient(135deg, #1A1008 0%, #8B6344 100%)',
  },
  fitness: {
    brand: 'Pulse Fitness',
    brandAr: 'نبض فيتنس',
    tagline: 'Premium training studio · Doha',
    taglineAr: 'استوديو تدريب premium · الدوحة',
    hero: '/portfolio/fitness-hero.jpg',
    preview: '/portfolio/fitness-hero.jpg',
    services: [
      { name: 'Personal', nameAr: 'شخصي', img: '/portfolio/fitness-s1.jpg', tone: '#FFCDD2', tone2: '#C62828', icon: 'trending' },
      { name: 'Classes', nameAr: 'حصص', img: '/portfolio/fitness-s2.jpg', tone: '#B0BEC5', tone2: '#37474F', icon: 'sparkles' },
      { name: 'Nutrition', nameAr: 'تغذية', img: '/portfolio/fitness-s3.jpg', tone: '#FFCCBC', tone2: '#E85D4C', icon: 'heart' },
    ],
    accent: '#E85D4C',
    accentLight: '#FF8A65',
    bg: '#F8F9FA',
    dark: '#0D1117',
    nav: ['Programs', 'Coaches', 'Pricing', 'Join'],
    navAr: ['برامج', 'مدربون', 'أسعار', 'انضم'],
    stat: '+64/mo',
    statLabel: 'Members',
    heroFallback: 'linear-gradient(135deg, #0D1117 0%, #E85D4C 100%)',
  },
};
